In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## Creating arrays using list

In [2]:
myList = [1,2,3,4,5,6]
np.array(myList)

array([1, 2, 3, 4, 5, 6])

In [3]:
myNestedList = [[1,2,3], [2,3,4],[4,5,6]]
np.array(myNestedList)

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [4]:
myList1 = [2,3,4]
myList2 = [3,4,5]
np.array([myList1, myList2])

array([[2, 3, 4],
       [3, 4, 5]])

## Creating arrays using functions

In [7]:
np.arange(6,17)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros(5, dtype= int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(6, dtype= int)

array([1, 1, 1, 1, 1, 1])

In [24]:
np.full((4,5),18.5)

array([[18.5, 18.5, 18.5, 18.5, 18.5],
       [18.5, 18.5, 18.5, 18.5, 18.5],
       [18.5, 18.5, 18.5, 18.5, 18.5],
       [18.5, 18.5, 18.5, 18.5, 18.5]])

In [16]:
np.full((5,5), 20, dtype =float)

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [13]:
np.info(np.ones)

 ones(shape, dtype=None, order='C')

Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
       [1.]])

>>> s = (2,2

In [45]:
x = np.array([1,2,9,0])#all gives True when no zero is there and false when at least one zero is there. 
print(x)
np.all(x)

[1 2 9 0]


False

In [50]:
h = np.array([0,0,0,0]) # if all values are zero then True and if a non zero value is present then False
print(h)
np.any(h)

[0 0 0 0]


False

In [51]:
a = np.array([0,2,3, np.nan, np.inf])   # nan = not_a_number , inf = infinite
a

array([ 0.,  2.,  3., nan, inf])

In [24]:
np.isinf(a)

array([False, False, False, False,  True])

In [26]:
np.isnan(a)

array([False, False, False,  True, False])

In [28]:
c = np.array([1+3j, 4, 3+7j, 8,9])
c

array([1.+3.j, 4.+0.j, 3.+7.j, 8.+0.j, 9.+0.j])

In [29]:
np.iscomplex(c)

array([ True, False,  True, False, False])

In [30]:
np.isreal(c)

array([False,  True, False,  True,  True])

## Comparison of arrays

In [53]:
x = np.array([1,2,3,4])
y = np.array([2,1,3,5])

In [32]:
np.greater(x,y)

array([False,  True, False, False])

In [33]:
np.less(x,y)

array([ True, False, False,  True])

In [34]:
np.greater_equal(x,y)

array([False,  True,  True, False])

In [54]:
np.less_equal(x,y)

array([ True, False,  True,  True])

In [55]:
v = np.identity(6, dtype= int)
print(v)

v.shape      #print shape of matrix

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


(6, 6)

In [25]:
np.random.normal(0,1)

-0.3534263878028253

In [29]:
A = np.arange(10,22).reshape(2,6)
A

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [33]:
v = np.linspace(10,50, 10 , dtype = int)
v

array([10, 14, 18, 23, 27, 32, 36, 41, 45, 50])

In [57]:
np.random.randint(0,11,6)       # will give 6 randome integers between 0 and 11

array([3, 1, 7, 4, 6, 9])

## Calculations

In [52]:
x = np.array([2,3,4,5])
y = np.array([3,5,6,7])
multiply = x*y

In [53]:
multiply

array([ 6, 15, 24, 35])

In [54]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [59]:
x = np.arange(1,13).reshape(4,3)
print(x)
np.sum(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


78

In [60]:
np.sum(x , axis=0) # columns 

array([22, 26, 30])

In [61]:
np.sum(x , axis= 1) # rows

array([ 6, 15, 24, 33])

In [62]:
x = np.array([1,2])
y = np.array([3,4])
np.dot(x,y)          # (1*3)+(2*4)

11

In [63]:
np.multiply(x,y)

array([3, 8])

In [63]:
np.outer(x,y)    #1*3  1*4
                 #2*3  2*4

array([[3, 4],
       [6, 8]])

In [64]:
np.zeros_like(x)         # overwrite all with 0

array([0, 0])

In [68]:
np.arange(0,45).reshape(3,5,3)  #reshape(3 matrix,5 rows,3 columns)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [37]:
np.__version__

'1.19.2'

## Broadcasting

In [39]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
newArr[:] = 200

In [41]:
newArr

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [42]:
newArr[4:6] = 20

In [43]:
newArr

array([200, 200, 200, 200,  20,  20, 200, 200, 200, 200])

## Copy

In [44]:
copy = newArr.copy()

In [45]:
copy

array([200, 200, 200, 200,  20,  20, 200, 200, 200, 200])

In [46]:
copy[:5] = 15

In [47]:
copy

array([ 15,  15,  15,  15,  15,  20, 200, 200, 200, 200])

## Sorting

In [48]:
unsorted = np.array([20,10,25,40,11])

In [49]:
unsorted.sort()

In [50]:
unsorted

array([10, 11, 20, 25, 40])

In [51]:
type(unsorted)

numpy.ndarray

## Indexing

In [71]:
arr2d = np.arange(25).reshape(5,5)

In [72]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr2d[2:4,1:4]  # arr[ row_start:row_end , elemt_start:elemt_end ]

array([[11, 12, 13],
       [16, 17, 18]])

In [88]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
arr2d[1][3]

8

In [80]:
arr2d[2:4,:3]  

array([[10, 11, 12],
       [15, 16, 17]])

In [57]:
arr2d[2:5,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr2d[:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

## Conditional

In [59]:
newArr = np.arange(1,11)

In [60]:
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
newArr[newArr>5]

array([ 6,  7,  8,  9, 10])

In [62]:
newArr[newArr==6]

array([6])